# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_hash',
            new_name='event_tags',
        ),
    ]
